typography_spectrum: 0.21550952084362507
color:
  brandColors:
    - '#faf3e1'
    - '#632ad0'
    - '#cb8a37'
    - '#604922'
    - '#001100'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.9386905673891306
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.15413541346788406
analytics:
  google: UA-77421442-1
  facebook: null
  twitter: null
author:
  name: Deacon Patrick Jones
  email: lamontglen@mac.com
  url: www.MindYourHeadCoop.org
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3c12c13d-3ccd-4f4d-991f-068715aa713b.jpg
name: Mind Your Head Co-op
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Give
    id: 2adfef1c-8b41-4412-ad2a-c0ee75b67ddf
    type: content
  - name: About
    id: a5524d76-67c2-4107-8cf4-3c2820c56abf
    type: content
  - name: Start Healing
    id: 5014cfb3-d385-44db-88db-06f812341142
    type: content
  - name: Grieving a TBI to Heal a TBI
    id: 6013db31-87ee-4bb9-abc4-f167f0b5f76f
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c3e03ac8-4e72-4ae3-a20f-e156baf25073.jpg
title: Mind Your Head Co-op
description: 'Your life, your brain, you''re healing!'
purpose: []
