name: Mind Your Head Co-op
favicon: null
layout_spectrum: 0.37422
typography_spectrum: 0.42535
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#632ad0'
    - '#cb8a37'
    - '#61605f'
    - '#0d0900'
  brandStrength: 0.19557631947100163
  lightness: 0.2611754897516221
  saturation: 0.9386905673891306
  rhythmicContrast: 0.25
purpose: []
