name: Mind Your Head Co-op
favicon: null
layout_spectrum: 0.49642
typography_spectrum: 0.43606
title: Mind Your Head Co-op
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77421442-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#faf3e1'
    - '#632ad0'
    - '#cb8a37'
    - '#604922'
    - '#001100'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.9386905673891306
  rhythmicContrast: 1
purpose: []
